# Generated by Django 2.2.4 on 2020-05-20 12:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='fav_of_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
